### PR TITLE
WIP: Provisioning for docker on Windows

### PR DESCRIPTION
**Pull request by AColo89**
The first version of provisioning scripts to install docker on Windows

### CODE REVIEW

**Comment by paolomainardi** [comment]
Thank you @AColo89, this is a great addition!
I would like to investigate also the Docker for Windows solution, which should simplify a lot the windows provisioning.

**Comment by AColo89** [comment]
In the last commit, I added dinghy http proxy to avoid the issues related to the use of one or more containers that run simultaneously different applications on the same port. 
And I added the code, in Powershell scripts for windows provisioning, to install the Carbon module. Which is a Powershell module with differents scripts that allows us to improve the configuration of Windows applications, websites, and services. But in this specific case, this module helps us to add and remove a new DNS alias from the Windows hosts file

**Comment by AColo89** [comment]
> I would like to investigate also the Docker for Windows solution, which should simplify a lot the windows provisioning.

What do you mean? I already used Docker for Windows. Maybe would you like to find a way to remove it?

**Comment by paolomainardi** [comment]
> > I would like to investigate also the Docker for Windows solution, which should simplify a lot the windows provisioning.
> 
> @paolomainardi What do you mean? I already used Docker for Windows. Maybe would you like to find a way to remove it?

Ciao @AColo89, it seems that we are custom provisioning an Ubuntu WSL2 VM instead with docker for windows (https://hub.docker.com/editions/community/docker-ce-desktop-windows) we don't need that, am i missing something ?

**Comment by AColo89** [comment]
> it seems that we are custom provisioning an Ubuntu WSL2 VM instead with docker for windows (https://hub.docker.com/editions/community/docker-ce-desktop-windows) we don't need that, am i missing something ?

We can use different distributions but I'm focusing on Ubuntu, for now, maybe I can add only the provisioning scripts for different distributions and I could avoid installing Ubuntu distribution. But it isn't a constraint for the provisioning.

**Comment by paolomainardi** [comment]
@AColo89 yes, i mean that just using Docker for windows we don't need to maintain a custom linux distribution because it's managed by them, i propose you a quick call just to show you how we are planning to support this scenario on the Mac silicon architecture.

**Pull request closed without merging**
