### PR TITLE
OSX  10.15 Catalina updates

### PR DESCRIPTION
**Pull request by alessiopiazza**

### CODE REVIEW

**Comment by paolomainardi** [comment]
@alessiopiazza split this configurations in an another file just for Catalina, so we don't break the compatibility with 10.14.

**Comment by paolomainardi** [comment]
@alessiopiazza is it something that you can take in charge ? I am pressing about this because i need it soon.

**Comment by alessiopiazza** [comment]
Sorry felt out of my radar. Should be able to improve this soon

**Comment by paolomainardi** [comment]
OK thanks, the idea is to split the configurations.

**Comment by alessiopiazza** [comment]
@paolomainardi give it a try

**Comment by alessiopiazza** [comment]
must be merged first

**Pull request merged**
